utils:
  task_type: 3dlane
  task_name: ws3dlane
  output_prefix: "./ws3dlane_sup/train"
dataset:
  train:
    json_path: ['./data_splits/standard/train.json']
    data_rt: ['./dataset/Apollo_Sim_3D_Lane_Release']
  val:
    json_path: ['./data_splits/standard/test.json']
    data_rt: ['./dataset/Apollo_Sim_3D_Lane_Release']

weakly_supervised: false
resize_h: 360
resize_w: 480
ipm_h: 208
ipm_w: 128
org_h: 1080
org_w: 1920
crop_y: 0
top_view_region: [[-10, 100], [10, 100], [-10, 0], [10, 0]]
K: [[2015, 0, 960], [0, 2015, 540], [0, 0, 1]]
num_y_steps: 20
anchor_y_steps: [0.001, 2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100]
y_ref: 5.0
prob_th: 0.5
batch_norm: true
no_centerline: true
no_3d: false
no_cuda: false
fix_cam: false
pred_cam: false
use_double_x_anchor: false
pitch: 3
cam_height: 1.55
input_mean: [0.485, 0.456, 0.406]
input_std: [0.229, 0.224, 0.225]

data_loader:
  num_workers: 4
  input_shape: [3, 360, 480]
  input_mean: [0.485, 0.456, 0.406]
  input_std: [0.229, 0.224, 0.225]
  camara_intrin: [[2015, 0, 960], [0, 2015, 540], [0, 0, 1]]

batch_size: 16

train:
  pretrain:
    active: false
    param_path: ''
  num_workers: 1
  epochs: 100
  frequent: 5
  model_prefix: ''
  optimizer: 'adam'
  lr: 0.001
  lr_scheduler: 'lamda'
  warmup_epoches: 10
  wd: 0.0002

  init:
    initializer: 'kaiming_normal'
    params: {
      'value': 1.0,
      'scale': 0.1,
      'sigma': 0.01,
      'gain': 1,
    }

